
services:

  who:
    image: containous/whoami:${WHO_VERSION:-latest}
    container_name: ${TANGO_APP_NAME}_who
    depends_on: 
      - service_init
    restart: unless-stopped
    labels:
      - "${TANGO_INSTANCE_NAME}.managed=true"
      - "traefik.enable=true"
      # service : who
      - "traefik.http.services.who.loadbalancer.server.port=80"
      - "traefik.http.services.who.loadbalancer.server.scheme=http"
      - "traefik.http.services.who.loadbalancer.passhostheader=true"
      # middlewares : who
      # service router : who
      - "traefik.http.routers.who.entrypoints=${WHO_ENTRYPOINTS:-entry_main_http}"
      - "traefik.http.routers.who.rule=HostRegexp(`{subdomain:who}.{domain:${TANGO_DOMAIN:-.*}}`)"
      - "traefik.http.routers.who.priority=${WHO_PRIORITY}"
      - "traefik.http.routers.who.service=who"
      - "traefik.http.routers.who-secure.entrypoints=${WHO_ENTRYPOINTS_SECURE:-entry_main_http_secure}"
      - "traefik.http.routers.who-secure.rule=HostRegexp(`{subdomain:who}.{domain:${TANGO_DOMAIN:-.*}}`)"
      - "traefik.http.routers.who-secure.priority=${WHO_PRIORITY}"
      - "traefik.http.routers.who-secure.service=who"
      - "traefik.http.routers.who-secure.tls=true"
      - "traefik.http.routers.who-secure.tls.domains[0].main=who.${TANGO_DOMAIN:-.*}"
      # service router middlewares : who
    networks:
      - default
    expose:
      - 80
