#!/bin/bash
_CURRENT_FILE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
_CURRENT_RUNNING_DIR="$( cd "$( dirname "." )" && pwd )"


# stella framework log
[ "$STELLA_LOG_STATE" = "" ] && STELLA_LOG_STATE="OFF"
[ "$STELLA_LOG_LEVEL" = "" ] && STELLA_LOG_LEVEL="INFO"
# tangp logs
[ "$TANGO_LOG_STATE" = "" ] && TANGO_LOG_STATE="ON"
[ "$TANGO_LOG_LEVEL" = "" ] && TANGO_LOG_LEVEL="INFO"
# note : $STELLA_API set_log_level_app is not yet available
STELLA_APP_LOG_STATE="$TANGO_LOG_STATE"
STELLA_APP_LOG_LEVEL="$TANGO_LOG_LEVEL"
#export STELLA_LOG_STATE=$STELLA_LOG_STATE

. "${_CURRENT_FILE_DIR}/tango-link.sh" "set-tango-root include-stella"

$STELLA_API log_app "INFO" "salsa" "welcome to salsa"

case $1 in
    lgsm)
        case $2 in
            build)
                docker build -t studioetrange/linuxgsm-docker:latest https://github.com/StudioEtrange/linuxgsm-docker.git
            ;;

            *)
                "${TANGO_ROOT}/tango" --ctx salsa --ctxroot ${_CURRENT_FILE_DIR} exec $2 --module $2 -- /home/linuxgsm/linuxgsm/lgsm-gameserver $3
            ;;
        esac
    ;;

    *)
        "${TANGO_ROOT}/tango" --ctx salsa --ctxroot ${_CURRENT_FILE_DIR} $*
    ;;

esac

 