#!/bin/bash
_CURRENT_FILE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
_CURRENT_RUNNING_DIR="$( cd "$( dirname "." )" && pwd )"



# INIT TANGO -------------------
# TANGO lookup order
#       1. externaly defined TANGO_ROOT     ==> instance mode : isolated or shared
#       2. "${_CURRENT_FILE_DIR}/../tango"  ==> instance mode : isolated or shared
#       3. "salsa/tango"                    ==> instance mode : isolated only. shared instance is not compatible with this location
INTERNAL_TANGO_ROOT="${_CURRENT_FILE_DIR}/tango"
INSTANCE_MODE_SHARED_OK=
if [ "${TANGO_ROOT}" = "" ]; then
    if [ -d "${_CURRENT_FILE_DIR}/../tango" ]; then
        TANGO_ROOT="${_CURRENT_FILE_DIR}/../tango"
        INSTANCE_MODE_SHARED_OK=1
    else
        # use internal tango
        TANGO_ROOT="${INTERNAL_TANGO_ROOT}"
    fi
else
    TANGO_ROOT="$(cd "${TANGO_ROOT}" && pwd -P)"
    [ ! "${TANGO_ROOT}" = "${INTERNAL_TANGO_ROOT}" ] && INSTANCE_MODE_SHARED_OK=1
fi

if [ ! -d "${TANGO_ROOT}" ]; then
    echo "* ERROR tango not found, by default it is first lookup into ${_CURRENT_FILE_DIR}/../tango OR defined its path with TANGO_ROOT"
    exit 1
fi

if [ "$1" = "build-lgsm" ]; then
    docker build -t studioetrange/linuxgsm-docker:latest https://github.com/StudioEtrange/linuxgsm-docker.git
else
    "${TANGO_ROOT}"/tango --app salsa --approot ${_CURRENT_FILE_DIR} $@
fi

 